[project]
name = "ml-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard-no-fastapi-cloud-cli]==0.121.3",
    "lightgbm==4.6.0",
    "pandas>=2.3.3",
    "scikit-learn==1.7.1",
]
